// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ3LtIS87jRffyrq0Cyxb9QbtpNDf_0DM',
    appId: '1:841408435990:android:b07128fa828e526e546237',
    messagingSenderId: '841408435990',
    projectId: 'chatopea-230dd',
    storageBucket: 'chatopea-230dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLNnXo7Uj55fx_OwGRa_Pzjjqus6htZLs',
    appId: '1:841408435990:ios:d05d44d5878b995f546237',
    messagingSenderId: '841408435990',
    projectId: 'chatopea-230dd',
    storageBucket: 'chatopea-230dd.appspot.com',
    androidClientId: '841408435990-q47k5k2q5q0hmock4fp981qb41a24ba6.apps.googleusercontent.com',
    iosClientId: '841408435990-2gijna6i6f32dtnks952kdgfo2a0a0f7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatopeas',
  );
}
